- name: Setup PHP Action
  uses: shivammathur/setup-php@2
on: workflow_dispatch
jobs:
  run:
    runs-on: [ubuntu-latest, windows-latest]
    name: Setup PHP TS
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: redis, xlswriter
      env:
        phpts: nts # specify ts or nts