on: workflow_dispatch
jobs:
  run:
    runs-on: [windows-latest]
    name: Setup PHP nts
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: redis, xlswriter
        env:
          phpts: nts # specify ts or nts