- name: Build the extension
  uses: php/php-windows-builder/extension@v1
  with:
    extension-url: https://github.com/phpredis/phpredis
    extension-ref: '6.0.2'
    php-version: '8.3'
    ts: nts
    arch: x64
    args: --enable-redis
    libs: zlib
